version: "3.5"

services:

  nginx:
    container_name: hismith-nginx
    hostname: hismith-nginx
    build:
      context: ./docker/nginx/
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8988:80"
    depends_on:
      - php
      - db
    networks:
      - hismith-network

  php:
    container_name: hismith-php
    hostname: hismith-php
    build:
      context: ./docker/php/
    volumes:
      - ./:/app:delegated
    environment:
      APP_LOCALE: en
    ports:
      - "9999:9000"
    depends_on:
      - db
    networks:
      - hismith-network

  db:
    container_name: hismith-db
    hostname: hismith-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - hismith-mysql:/var/lib/mysql
    ports:
      - "${MYSQL_SERVER_FORWARD_PORT:-53346}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-hismith}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    networks:
      - hismith-network


volumes:
  hismith-mysql: {}

networks:
  hismith-network:
    name: hismith-network
